// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from "react-cosmos-core";

import * as fixture0 from "./app/components/UserActions/UserActions.fixture.jsx";
import * as fixture1 from "./app/components/RawConfig/RawConfig.fixture.jsx";
import * as fixture2 from "./app/components/QrCode/QrCode.fixture.jsx";
import * as fixture3 from "./app/components/PropTable/PropTable.fixture.jsx";
import * as fixture4 from "./app/components/ProgressCard/ProgressCard.fixture";
import * as fixture5 from "./app/components/Popover/Popover.fixture.jsx";
import * as fixture6 from "./app/components/Metrics/Metrics.fixture.jsx";
import * as fixture7 from "./app/components/EventList/EventList.fixture.jsx";
import * as fixture8 from "./app/components/EventHistory/EventHistory.fixture.jsx";
import * as fixture9 from "./app/components/EventCard/EventCard.fixture.jsx";
import * as fixture10 from "./app/components/CodeScanner/CodeScanner.fixture.jsx";
import * as fixture11 from "./app/components/BugModal/BugModal.fixture.jsx";
import * as fixture12 from "./app/components/AssetTable/AssetTable.fixture.jsx";
import * as fixture13 from "./app/components/AssetLink/AssetLink.fixture.jsx";

export const rendererConfig: RendererConfig = {
  playgroundUrl: "http://localhost:5000",
  rendererUrl: "http://localhost:3000/cosmos",
};

const fixtures = {
  "app/components/UserActions/UserActions.fixture.jsx": { module: fixture0 },
  "app/components/RawConfig/RawConfig.fixture.jsx": { module: fixture1 },
  "app/components/QrCode/QrCode.fixture.jsx": { module: fixture2 },
  "app/components/PropTable/PropTable.fixture.jsx": { module: fixture3 },
  "app/components/ProgressCard/ProgressCard.fixture.tsx": { module: fixture4 },
  "app/components/Popover/Popover.fixture.jsx": { module: fixture5 },
  "app/components/Metrics/Metrics.fixture.jsx": { module: fixture6 },
  "app/components/EventList/EventList.fixture.jsx": { module: fixture7 },
  "app/components/EventHistory/EventHistory.fixture.jsx": { module: fixture8 },
  "app/components/EventCard/EventCard.fixture.jsx": { module: fixture9 },
  "app/components/CodeScanner/CodeScanner.fixture.jsx": { module: fixture10 },
  "app/components/BugModal/BugModal.fixture.jsx": { module: fixture11 },
  "app/components/AssetTable/AssetTable.fixture.jsx": { module: fixture12 },
  "app/components/AssetLink/AssetLink.fixture.jsx": { module: fixture13 },
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators,
};
